# Site settings
title: Gonzalo Ayuso
tagline: Web Architect
email: gonzalo123@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog since 2008
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics: 'G-HLM742Z1VH'
disqus_shortname: 'gonzalo123-com'
disable_landing_page: true

author:
  name: 'Gonzalo Ayuso'
  email: gonzalo123@gmail.com
  twitter_username: gonzalo123
  github_username:  gonzalo123
  linkedin_username:  gonzaloayuso

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 20
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
exclude: [
    'README.md',
    'Gemfile',
    'Gemfile.lock',
    'screenshot.png',
    'output/*'
]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.

liquid:
  error_mode: lax
